add invild state for nrwl update

diff --git a/.github/workflows/deps-nrwl_update.yml b/.github/workflows/deps-nrwl_update.yml
--- a/.github/workflows/deps-nrwl_update.yml
+++ b/.github/workflows/deps-nrwl_update.yml
@@ -15,23 +15,32 @@ jobs:
         with:
           fetch-depth: 0
 
-      - uses: actions/cache@v2
-        with:
-          path: '**/node_modules'
-          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
+      # - uses: actions/cache@v2
+      #   with:
+      #     path: '**/node_modules'
+      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: 16
+      # - name: Set up Node.js
+      #   uses: actions/setup-node@v2
+      #   with:
+      #     node-version: 16
 
-      - name: Install dependencies
-        run: yarn
+      # - name: Install dependencies
+      #   run: yarn
+
+      # - name: NRWL Update
+      #   id: nrwl_update
+      #   continue-on-error: true
+      #   run: |
+      #     yarn update
+      #     yarn format
 
       - name: NRWL Update
+        id: nrwl_update
+        continue-on-error: true
         run: |
-          yarn update
-          yarn format
+          echo 'hello world' > test.txt
+          exit 1
 
       - name: Check for changes
         run: |
@@ -40,8 +49,13 @@ jobs:
           else
             echo "CHANGED_FILES=true" >> $GITHUB_ENV
           fi
+          echo "LABELS=dependencies" >> $GITHUB_ENV
           echo "BRANCH=nrwl_update_$(date +'%Y_%m_%d')" >> $GITHUB_ENV
           echo "TITLE=NRWL Update $(date +'%d.%m.%Y')" >> $GITHUB_ENV
+
+      - name: Add invalid Label
+        if: ${{ steps.nrwl_update.outcome == 'failure' }}
+        run: echo "LABELS=${{ env.LABELS }},invalid" >> $GITHUB_ENV
 
       - name: Create Branch
         if: env.CHANGED_FILES == 'true'
@@ -55,6 +69,6 @@ jobs:
 
       - name: Create Pull Request
         if: env.CHANGED_FILES == 'true'
-        run: gh pr create --title '${{ env.TITLE }}' --body '**Automated pull request**' --base main --head ${{ env.BRANCH }} --label 'dependencies'
+        run: gh pr create --title '${{ env.TITLE }}' --body '**Automated pull request**' --base main --head ${{ env.BRANCH }} --label '${{ env.LABELS }}'
         env:
           GITHUB_TOKEN: ${{secrets.PAT}}
